services:
  - type: web
    name: neurodoc-app
    env: python
    plan: free
    region: oregon
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
    buildFilter:
      paths:
        - requirements.txt
        - app.py
        - templates/**
        - static/**
        - neurodoc_core/**
